kong: # incase of 'kong' chart as a sub-chart
  # -----------------------------------------------------------------------------
  # Miscellaneous parameters
  # -----------------------------------------------------------------------------
  # Kong pod count.
  # It has no effect when autoscaling.enabled is set to true
  replicaCount: 2

  # Enable autoscaling using HorizontalPodAutoscaler
  # When configuring an HPA, you must set resource requests on all containers via
  # "resources" and, if using the controller, "ingressController.resources" in values.yaml
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 60

  # update strategy
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: "50%"

  # -----------------------------------------------------------------------------
  # Ingress Controller parameters
  # -----------------------------------------------------------------------------
  ingressController:
    enabled: false

  # -----------------------------------------------------------------------------
  # Kong parameters
  # -----------------------------------------------------------------------------
  env:
    database: "off"
  admin:
    enabled: true
    type: ClusterIP
  proxy:
    enabled: true
    type: LoadBalancer
  status:
    enabled: true
  enterprise:
    enabled: false
  manager:
    enabled: false
  portal:
    enabled: false
  portalapi:
    enabled: false