---
# Source: simplenodejs/charts/simple-nodejs/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-poc-simple-nodejs
  labels:
    helm.sh/chart: simple-nodejs-0.1.0
    app.kubernetes.io/name: simple-nodejs
    app.kubernetes.io/instance: service-poc
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: simple-nodejs
    app.kubernetes.io/instance: service-poc
---
# Source: simplenodejs/charts/simple-nodejs/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-poc-simple-nodejs
  labels:
    helm.sh/chart: simple-nodejs-0.1.0
    app.kubernetes.io/name: simple-nodejs
    app.kubernetes.io/instance: service-poc
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-nodejs
      app.kubernetes.io/instance: service-poc
  template:
    metadata:
      labels:
        helm.sh/chart: simple-nodejs-0.1.0
        app.kubernetes.io/name: simple-nodejs
        app.kubernetes.io/instance: service-poc
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: default
      containers:
        - name: simple-nodejs
          image: "node:23.9.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: simplenodejs/charts/simple-nodejs/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-poc-simple-nodejs
  labels:
    helm.sh/chart: simple-nodejs-0.1.0
    app.kubernetes.io/name: simple-nodejs
    app.kubernetes.io/instance: service-poc
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-poc-simple-nodejs
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
---
# Source: simplenodejs/charts/simple-nodejs/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "service-poc-simple-nodejs-test-connection"
  labels:
    helm.sh/chart: simple-nodejs-0.1.0
    app.kubernetes.io/name: simple-nodejs
    app.kubernetes.io/instance: service-poc
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['service-poc-simple-nodejs:80']
  restartPolicy: Never
